# Generated by Django 5.0 on 2023-12-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Slider_image', models.ImageField(upload_to='media/Slider')),
                ('deal', models.CharField(choices=[('New Deal', 'New Deal'), ('New Arrivals', 'New Arrivals'), ('Hot Deals', 'Hot Deals')], max_length=200)),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
    ]
