# Generated by Django 5.0 on 2023-12-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
