# Generated by Django 5.0 on 2023-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default='media\\media\\Slider\\01-slide-2.jpg', upload_to='media/Feature'),
        ),
        migrations.AddField(
            model_name='feature',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Slider_image',
            field=models.ImageField(default='', upload_to='media/Slider'),
        ),
    ]
