# Generated by Django 5.0 on 2024-01-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_orders_razorpay_order_id_orders_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
