# Generated by Django 5.0 on 2024-01-15 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_useraddress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached', models.CharField(blank=True, max_length=220, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orders')),
            ],
        ),
    ]
