# Generated by Django 5.0 on 2024-01-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
