# Generated by Django 5.0 on 2024-01-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_orderproducts_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='verified',
        ),
        migrations.AddField(
            model_name='comments',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
